WITH products AS (
    SELECT * FROM {{ ref('snapshot_products') }}
)
 
SELECT 
    CAST(SKU AS VARCHAR(30)) AS SKU,
    CAST(NAME AS VARCHAR(255)) AS NAME,
    CAST(TYPE AS VARCHAR(30)) AS TYPE,
    CAST(PRICE AS NUMERIC(9,2)) AS PRICE,
    CAST(DESCRIPTION AS VARCHAR(255)) AS DESCRIPTION,
    DBT_VALID_FROM,
    DBT_VALID_TO,
    CAST(SOURCE AS VARCHAR(100)) AS SOURCE,
    CAST(INGESTION_DATE AS DATETIME) AS INGESTION_DATE,
    GETDATE() AS UPDATE_DATE
FROM products