WITH stores AS (
    SELECT *
    FROM {{ source('JAFFLE_SHOP', 'raw_stores') }}
)

SELECT
    CAST(ID AS VARCHAR(100)) AS ID,
    CAST(NAME AS VARCHAR(30)) AS NAME,
    CAST(OPENED_AT AS DATE) AS OPENED_DATE,
    CAST(TAX_RATE AS FLOAT) AS TAX_RATE,
    CAST(SOURCE AS VARCHAR(100)) AS SOURCE,
    GETDATE() AS UPDATE_DATE
FROM stores