WITH order_items AS (
    SELECT TOP 10 *
    FROM {{ source('JAFFLE_SHOP', 'raw_order_items') }}
)

SELECT
    CAST(ID AS VARCHAR(100)) AS ID,
    CAST(ORDER_ID AS VARCHAR(100)) AS ORDER_ID,
    CAST(SKU AS VARCHAR(30)) AS SKU,
    CAST(SOURCE AS VARCHAR(100)) AS SOURCE,
    CAST(INGESTION_DATE AS DATETIME) AS INGESTION_DATE,
    GETDATE() AS UPDATE_DATE
FROM order_items