version: 2

sources:
  - name: JAFFLE_SHOP
    schema: RAW
    tables:
      - name: raw_products
        identifier: raw_products
        columns:
          - name: SKU
            description: 'Product identifier' 

          - name: NAME
            description: 'Product name'

          - name: TYPE
            description: 'Product type'

          - name: PRICE
            description: 'Current price of the product'

          - name: DESCRIPTION
            description: 'Product description'

          - name: SOURCE
            description: 'Path location of ingestioned data'

          - name: INGESTION_DATE
            description: 'Data ingestion timestamp'

      - name: raw_customers
        identifier: raw_customers
        columns:
          - name: ID
            description: 'Customer identifier'

          - name: NAME
            description: 'Customer name'

          - name: SOURCE
            description: 'Path location of ingestioned data'

          - name: INGESTION_DATE
            description: 'Data ingestion timestamp'

      - name: raw_orders
        identifier: raw_orders
        columns:
          - name: ID
            description: 'Order identifier'

          - name: CUSTOMER
            description: 'Customer identifier'

          - name: ORDERED_AT
            description: 'Order date'

          - name: STORE_ID
            description: 'Store identifier'

          - name: SUBTOTAL
            description: 'Total amount of the order, not including tax'

          - name: 'TAX_PAID'
            description: 'Total tax amount paid in the order'

          - name: ORDER_TOTAL
            description: 'Total amount of the order, including tax'
          
          - name: SOURCE
            description: 'Path location of ingestioned data'

          - name: INGESTION_DATE
            description: 'Data ingestion timestamp'